<Project Sdk="Microsoft.NET.Sdk" ToolsVersion="15.0">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PackageTags>dotnet cli packaging deb debian ubuntu mint installer</PackageTags>
    <Description>Create Debian and Ubuntu installers (.deb files ) of your .NET Core projects straight from the command line.

Once you've installed this package as a .NET CLI tool, run dotnet deb to generate a .deb file which contains the publish output of your .NET Project.

See https://github.com/qmfrederik/dotnet-packaging/ for more information on how to use dotnet deb.</Description>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>dotnet-deb</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="3.0.0-preview.6.26359.118" />
    <PackageReference Include="Microsoft.Build" Version="18.8.2" ExcludeAssets="runtime" />
    <PackageReference Include="Microsoft.Build.Locator" Version="1.11.2" />
  </ItemGroup>
  
  <ItemGroup>
    <Compile Include="..\dotnet-rpm\PackagingRunner.cs" Link="PackagingRunner.cs" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Update="Microsoft.SourceLink.GitHub" Version="11.0.100-preview.6.26359.118" />
    <PackageReference Update="NerdBank.GitVersioning" Version="3.11.13-beta" />
  </ItemGroup>
</Project>